## Homework Assignment 1 - NumPy Exercises for Beginners
NumPy is a computational library that helps in speeding up Vector Algebra operations that involve Vectors (Distance between points, Cosine Similarity) and Matrices. Specifically, it helps in constructing powerful n-dimensional arrays that works smoothly with distributed and GPU systems. It is a very handy library and extensively used in the domains of Data Analytics and Machine Learning. Other than Python, it can also be used in tandem with languages like C and Fortran. Being an Open Source Library under a liberal BSD license, it is developed and maintained publicly on GitHub. 

### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

### 2. Create random vector of size 10 and replace the maximum value by 0

In [2]:
v = np.random.rand(10)
print(v)
v = np.where(v==max(v), [0]*10, v)
v


[0.71054405 0.6686429  0.36089601 0.84133875 0.44636368 0.70114554
 0.38706943 0.84109883 0.86200546 0.61799173]


array([0.71054405, 0.6686429 , 0.36089601, 0.84133875, 0.44636368,
       0.70114554, 0.38706943, 0.84109883, 0.        , 0.61799173])

### 3. Create a 5*5 martrix whose main diagonal elements as `1,2,3,4,5` and other elements as `0`

In [3]:
m = np.zeros([5,5],dtype=int)
for i in range(5):
    for j in range(5):
        if i == j:
            m[i][j]=i+1
m

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### 4. Create a 10*10 martrix whose boundary values as 1 and internal values as 0

In [4]:
m = np.ones([10,10])
m[1:-1,1:-1] = np.zeros([8,8])
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])